### PR TITLE
Make it easier for people to get a mental model and manage deps

### PR DESCRIPTION
**Pull request by whatisaghostwriter**
I recently converted all of my projects to monorepos using either yarn or pnpm workspaces, whichever gives me the most luck.
This can be setup with either, I'll leave that decision to you. 
I do believe it makes more sense this way whereas before I would be against it with experiencing lerna.

### CODE REVIEW

**Comment by TomYeoman** [comment]
> I recently converted all of my projects to monorepos using either yarn or pnpm workspaces, whichever gives me the most luck. This can be setup with either, I'll leave that decision to you. I do believe it makes more sense this way whereas before I would be against it with experiencing lerna.

This is really cool, thanks for spending the time to manage this, I can definitely agree it's better managed with a workspace solution. 

This is the first time I have seen pnpm used for workspace management, and after looking into it looks like a solid solution, I like its approach to `node_modules` versus the latest yarn (although it seems you can setup yarn to use this solution also https://yarnpkg.com/package/@yarnpkg/plugin-pnpm).

I would like to ask what makes you choose use pnpm over lerna specifically for a project?

**Comment by TomYeoman** [comment]
@whatisaghostwriter I spent some time trying to run this locally, and get a bunch of issues, was this working locally for you first time?

I opened a branch against this project, which contains your commits, and one I've just added to fix the issues - https://github.com/TomYeoman/2d-zombie-survival-io-demo/pull/2

Would be great to get your eyes on it. 

Only issue left is that I cannot build now in `server` (only the `debug` command works) 
image

**Comment by whatisaghostwriter** [comment]
I see what's going on now, previously I've whipped up other repos this way, but there's always edge cases, The reason I don't use lerna is its just a lot slower than either of these tools. I've had a similar problem with resolution in pnpm and that's why I mentioned that I often opt for one or the other never did I think of this.

**Comment by whatisaghostwriter** [comment]
So the verdict is that that plugin is included with yarn v3 no need to install it. As for working on the issue using pnpm I was going to make a branch 3d engine, so I didn't make drastic changes to the pull request. I was aware of the dependency issues but somehow my state wasn't clean and it worked. I was looking to resolve them by upgrading packages instead of switching to yarn v3 or the latter yarn v1 which I resorted to on other projects. Some projects I have like in react-native monorepo still rely on the module resolutions option in yarn and I had a hard time trying to make it work with pnpm. So now with this yarnv3 workspaces setup you get these type errors
error 1
phaser2-
phaser-types

This could also be mismatched dependencies? I see 1 version of phaser in common and another in server, I wonder if I did that. "3.22.0" versus "phaser": "~3.24.1" in common.

As for using pnpm workspaces with yarn I was a bit confused for a moment

**Comment by TomYeoman** [comment]
Thanks for the explanation @whatisaghostwriter just to confirm the latest with this PR, is that you receive the error you posted above, when trying to use yarn 3?

Yeah the phaser version should be able to be the same across all packages

Is it not possible to solve the pnpm issue, whereby there was multiple react-types package being installed?

**Comment by whatisaghostwriter** [comment]
I plan on searching the pnpm issue. If it's not possible I suspect it being nengi can't go past node 14 so the dependencies required aren't available for esm modules / deprecated

**Pull request closed without merging**
